owner: luqaska
repo: ort

sites:
  - name: Campus
    url: https://campus.ort.edu.ar
    icon: https://external-content.duckduckgo.com/ip3/campus.ort.edu.ar.ico
  - name: CREA
    url: https://crea.ort.edu.ar
    icon: https://raw.githubusercontent.com/luqaska/ort/master/assets/logocrea.png
  - name: Editorial ORT
    url: https://editorial.ort.edu.ar
  - name: Extranet
    url: http://extranet.ort.edu.ar
  - name: F.M.
    url: $DRIVE
  - name: ORT
    url: https://www.ort.edu.ar
  - name: Descargas
    url: $RWDL

status-website:
  baseUrl: /ort/
  logoUrl: https://raw.githubusercontent.com/luqaska/ort/master/assets/ndflg.jpg
  name: ""
  introTitle: "Estado de los servidores de ORT"
  introMessage: "Página no oficial"
i18n:
  activeIncidents: Páginas caidas
  allSystemsOperational: Todas las webs están funcionando
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Detalles
  incidentFixed: Resuelto
  incidentOngoing: En proceso
  incidentOpenedAt: Detectado el
  incidentClosedAt: Cerrado hace
  incidentSubscribe: Subscribirse
  incidentViewOnGitHub: Ver en GitHub
  incidentCommentSummary: Posteado el $DATE por $AUTHOR
  incidentBack: ← Volver al lobby
  pastIncidents: Past Incidents
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: En vivo
  overallUptime: "Overall uptime: $UPTIME"
  overallUptimeTitle: Overall uptime
  averageResponseTime: "Average response time: $TIMEms"
  averageResponseTimeTitle: Average response
  sevelDayResponseTime: Últimos 7 dias
  responseTimeMs: Tiempo de respuesta (ms)
  up: ⬆
  down: ⬇
  degraded: Degradado
  loading: Cargando
  footer: Pwd by [Upptime](https://upptime.js.org)
  errorTitle: An error occurred Un error ha ocurrido
  errorIntro: Se produjo un error al intentar obtener los últimos detalles del estado.
  errorText: Intentalo de nuevo en unos minutos.
  errorHome: Ir al lobby
  pastScheduledMaintenance: Pasadas tareas de mantenimiento programadas
  scheduledMaintenance: Mantenimiento programado
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Empezó el
  startsAt: Empieza el
  duration: Duración
  durationMin: $DURATION mins.
  incidentCompleted: Completado
  incidentScheduled: Programado

skipDescriptionUpdate: true
skipTopicsUpdate: true
