owner: luqaska
repo: ort

sites:
  - name: Campus
    url: https://campus.ort.edu.ar
    #icon: https://external-content.duckduckgo.com/ip3/campus.ort.edu.ar.ico
  - name: CREA
    url: https://crea.ort.edu.ar
    #icon: https://raw.githubusercontent.com/luqaska/ort/master/assets/logocrea.png
  - name: Editorial ORT
    url: https://editorial.ort.edu.ar
  - name: Extranet
    url: http://extranet.ort.edu.ar
  - name: F.M.
    url: $DRIVE
  - name: ORT
    url: https://www.ort.edu.ar
  - name: Descargas
    url: $RWDL

status-website:
  baseUrl: /ort/
  logoUrl: https://raw.githubusercontent.com/luqaska/ort/master/assets/ndflg.jpg
  name: "TEST"
  introTitle: "Estado de los servidores de ORT"
  introMessage: "Página no oficial"
